### ISSUE TITLE
Installl libfoil with exec bit / rpm automatic provides miss to generate libfoil.so.1()(64bit)

### ISSUE THREAD

**Issue by ehdis** [monich/foil#2]
```
$ LANG=C rpm -V foil-tools
Unsatisfied dependencies for foil-tools-1.0.23-0.x86_64:
	libfoil.so.1()(64bit) is needed by (installed) foil-tools-1.0.23-0.x86_64
```

```
rpm -q --provides  libfoil
libfoil = 1.0.23-0
libfoil(x86-64) = 1.0.23-0
```

Should 

https://github.com/monich/foil/blob/master/libfoil/Makefile#L333

be 755? That would AFAIK allow that rpm's automatic-provides macro build a list with libfoil.so.1()(64bit) ...

**Comment by monich** [comment]
OK, I changed the shared library permissions to 755. That indeed seems to be a convention in the rpm world.

I doubt that it will make any difference, though. I never had such a problem with 64-bit ARM build, although I have to admit that I'm not an active user of x86-64 rpm-based systems.

**Comment by ehdis** [comment]
> OK, I changed the shared library permissions to 755. That indeed seems to be a convention in the rpm world.
> 
> I doubt that it will make any difference, though. I never had such a problem with 64-bit ARM build, although I have to admit that I'm not an active user of x86-64 rpm-based systems.


Confirmed: I had rebuild the package with that permission mode already and the auto-generated provides are complete now.
```
$ rpm -q libfoil --provides
libfoil = 1.0.23-0
libfoil(x86-64) = 1.0.23-0
libfoil.so.1()(64bit)
```

I think its more a question of the building context (rpm environment of the OS, in this case RHEL, FEDORA),
then a question of the hardware architecture (of course the provides entries corresponds to the respective arch).
