### ISSUE TITLE
compat for building on CentOS Stream 9 / RHEL 9  

### ISSUE THREAD

**Issue by ehdis** [monich/foil#3]
While trying to rpmbuild the master/1.0.25 branch on CentOS Stream 9 I noticed that the lib was created as "/usr/lib64/libfoil.so...".

Following patch helped to extract the right version:

```
--- libfoil-1.0.25/libfoil/Makefile.org	2022-10-08 22:51:41.000000000 +0200
+++ libfoil-1.0.25/libfoil/Makefile	2022-10-09 01:13:55.151724690 +0200
@@ -62,7 +62,7 @@
 #
 
 VERSION_FILE = $(INCLUDE_DIR)/foil_version.h
-get_version = $(shell grep -E "^ *\\\#define +FOIL_VERSION_$1 +[0-9]+$$" $(VERSION_FILE) | sed "s/  */ /g" | cut -d " " -f 3)
+get_version = $(shell grep -E "^ *\\#define +FOIL_VERSION_$1 +[0-9]+$$" $(VERSION_FILE) | sed "s/  */ /g" | cut -d " " -f 3)
 
 VERSION_MAJOR = $(call get_version,MAJOR)
 VERSION_MINOR = $(call get_version,MINOR)
```

BTW: 
1. SPEC: Requires: make, gcc
2. the "make check" don't pass while testing RSA stuff (segfaults) ... missing time to investigate that one ...

**Comment by monich** [comment]
Which version of openssl that CentOS Stream 9 thing has?

**Comment by ehdis** [comment]
Ok, I had more time now. So:
I did beforehand and complete rebuild of libglibutil-1.0.67 and libfoil-1.0.25-1.20221009git03c4ea7 
on the OS major version before CentOS Stream 9 (CS9) - speak CentOS Stream **8** (CS8). The rpm packages
were build more or less directly with a git clone and rpmbuild workflow without touching the code. 
The builds, packaging, install tests and decrypting test (foil-tools) were successful. 
The OS context of CS8:
```
[cs8 ~]$ rpm -q make openssl
make-4.2.1-11.el8.x86_64
openssl-1.1.1k-7.el8.x86_64
```

For the mentioned OS CentOS Stream 9 now: 
libglibutil-1.0.67 build straight forward. 
libfoil-1.0.25-1.20221009git03c4ea7 needed the mentioned patch for the makefile to build at least. 
A test while **disabling the checks** (uncommenting) produced an rpm package that could be installed.
On the CLI a decrypting test fails with exit code 139 and nil output. 

The OS context of CS9:
```
[cs9 ~] $ rpm  -q make openssl
make-4.3-7.el9.x86_64
openssl-3.0.1-41.el9.x86_64
```
So the mentioned patch only needed for the newer make. Not sure if the escaping syntax changed there. 
And for the crypto code - I assume that it is not compatible with **openssl-3**. So, you asked the right question.

Any plans for that? Thanks.

**Comment by monich** [comment]
Yeah, I was sort of expecting this. Thanks for heads up. And that's what unit tests are for 🙂
The plan is of course to move forward and add support for openssl 3 but there's no ETA for that yet.
The makefile issue is likely to be resolved sooner, when I install something that has make 4.3

**Comment by monich** [comment]
I just pushed some changes which should make this code work with OpenSSL 3.x

**Comment by monich** [comment]
And tagged it 1.0.26

**Comment by monich** [comment]
Thanks for heads-up!
